name: tiktok_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3
  flutter:
    sdk: flutter
  get: ^4.6.5
  image_picker: ^0.8.5+3
  video_compress: ^3.1.1
  video_player: ^2.4.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
